version: '3'
services:
  ca:
    build: ./docker/ca
    image: ktr0328/ca
    volumes:
      - './src/ca:/src/ca'
      - './node_modules:/src/node_modules'
    ports:
      - '3000:3000'
  service_server:
    build: ./docker/service
    image: ktr0328/service_server
    volumes:
      - './src/service:/src/service'
      - './node_modules:/src/node_modules'
    ports:
      - '4000:4000'
